### PR TITLE
[TASK] Update version number

### PR DESCRIPTION
**Pull request by unrevised6419**

### CODE REVIEW

**Comment by fsuter** [comment]
Good idea!

**Comment by iamandrewluca** [comment]
Can you please create last release again with this changes?
Composer it seems does not see version `3.1.2`

**Comment by fsuter** [comment]
Actually I noticed that last release was not correct. I created it, but forgot to change the version number. I don't think I can create a release again. I will create `3.1.3` instead.

**Comment by fsuter** [comment]
Done. I hope everything works out fine this time.

**Comment by unrevised6419** [comment]
Thanks! Now everything works fine.
`composer require cobweb/linkhandler` is installing version `3.1.3`

**Pull request merged**
