### PR TITLE
Fix replace section in composer.json

### PR DESCRIPTION
**Pull request by helhum**
Add first replace to match extension key and second to
communicate that this is a replacement for the TER extension.

### CODE REVIEW

**Comment by helhum** [comment]
The replace section is important in two regards:

1. The first replace is used as extension key
2. It is to communicate which other package/extension it is meant to replace

Additionally it is good to not announce to be a replacement for any of these versions, but only the current one

**Comment by fsuter** [comment]
OK, thanks for the explanations (I'm not really well informed about Composer) and thanks for the patch.

**Comment by fsuter** [comment]
@helhum Could this change have caused the error reported in https://github.com/cobwebch/linkhandler/issues/27 ?

**Comment by helhum** [comment]
Ah, a typo in the second version constraint. Sorry!

**Pull request merged**
