### PR TITLE
Code cleanup

### PR DESCRIPTION
**Pull request by liayn**

### CODE REVIEW

**Comment by fsuter** [comment]
Thanks for this work. Would it be correct to guess that this cleanup precedes an integration into TYPO3 8?

**Comment by fsuter** [comment]
BTW I just wonder about some reformatting. I am pretty sure I had applied PSR-2 formatting using PhpStorm. Is that not correct?

**Comment by liayn** [comment]
I have PSR-2 as well, so whatever happened, it reformatted stuff. No problem.

I talked to Benni and I will as a first step make the ext compatible with TYPO3 8. Benni want's to take a look at the link stuff in general, but doesn't have a time schedule ready. My plan is still to include this ext then into core, but maybe this happens in 2017 then.
We can use the time to make the ext as good as possible and write the necessary documentation.
We need the extension in a live-project with CMS 8 this month already, so I guess I need to finalize the adjustments for v8 somewhere next week.

**Comment by fsuter** [comment]
I see. It's true that there are a couple of pending bugs, which could be ironed out before integration, but I must admit that I have no energy to put into this, these days.

I'll try to put some pressure on Benni ;-) If all else fails, I'll try to officially hand over responsibility of linkhandler to someone else, because I don't really want to care for it anymore.

**Pull request merged**
